1:
  name: Radford
  company: com1
  discipline: Engineer
  position: SMTS
  math_of_interest: Prime
2:
  name: Matt
  company: com1
  discipline: Engineer
  position: Fellow
  math_of_interest: Factorial
3:
  name: Alireza
  company: com2
  discipline: Engineer
  position: SMTS
  math_of_interest: Fibonacci